version: 0.2

phases:
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm install
      - npm link @angular/cli
  build:
    commands:
      - ng build --prod
artifacts:
  files:
    - "**/*"