version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install --location=global
      - npm install --location=global @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod
artifacts:
  files:
    - "**/*"