version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install --location=global @angular/cli
      - npm install --location=global bootstrap
  build:
    commands:
      - echo Build started
      - ng build --prod
artifacts:
  files:
    - "**/*"