version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod
artifacts:
  files:
    - "**/*"
  base-directory: 'dist/nature-expedition'
  discard-paths: yes